FROM python:3.7.5-alpine
LABEL maintainer="narayanan.k.1985@gmail.com"

# Environment Build steps
RUN apk update && apk add build-base
#RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN pip install numpy
